{{- if  .Values.sealos }}
---
kind: App
metadata:
  name: aiproxy-admin
  namespace: ns-admin
spec:
  data:
    desc: sealos cloud aiproxy admin
    url: https://aiproxy.{{.Values.cloudDomain}}
  displayType: normal
  i18n:
    zh:
      name: AI Proxy 管理中心
    zh-Hans:
      name: AI Proxy 管理中心
  icon: https://aiproxy.{{.Values.cloudDomain}}/logo.svg
  name: Sealos AI Proxy Admin
  type: iframe
apiVersion: app.sealos.io/v1
{{- end }}