apiVersion: v1
data: {{ merge .Values.aiproxy (dict "DEFAULT_MCP_HOST" (printf "aiproxy.%s" .Values.cloudDomain)) | toYaml | nindent 2 }}
kind: ConfigMap
metadata:
  namespace: {{.Release.Namespace}}
  name: {{ include "aiproxy.fullname" . }}-env
  labels:
    {{- include "aiproxy.labels" . | nindent 4 }}
