apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    sealos-db-provider-cr: {{.Values.redis.name}}
    app.kubernetes.io/instance: {{.Values.redis.name}}
    app.kubernetes.io/managed-by: kbcli
  name: {{.Values.redis.name}}
  namespace: {{.Release.Namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    sealos-db-provider-cr: {{.Values.redis.name}}
    app.kubernetes.io/instance: {{.Values.redis.name}}
    app.kubernetes.io/managed-by: kbcli
  name: {{.Values.redis.name}}
  namespace: {{.Release.Namespace}}
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    sealos-db-provider-cr: {{.Values.redis.name}}
    app.kubernetes.io/instance: {{.Values.redis.name}}
    app.kubernetes.io/managed-by: kbcli
  name: {{.Values.redis.name}}
  namespace: {{.Release.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{.Values.redis.name}}
subjects:
  - kind: ServiceAccount
    name: {{.Values.redis.name}}
    namespace: {{.Release.Namespace}}
---
apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  labels:
    clusterdefinition.kubeblocks.io/name: redis
    clusterversion.kubeblocks.io/name: {{ .Values.redis.version }}
  name: {{.Values.redis.name}}
  namespace: {{.Release.Namespace}}
spec:
  affinity:
    nodeLabels: {}
    podAntiAffinity: Preferred
    tenancy: SharedNode
    topologyKeys:
      - kubernetes.io/hostname
  backup:
    cronExpression: {{.Values.redis.backup.cron}}
    enabled: true
    method: datafile
    pitrEnabled: true
    retentionPeriod: {{.Values.redis.backup.retentionPeriod}}
  clusterDefinitionRef: redis
  clusterVersionRef: {{ .Values.redis.version }}
  componentSpecs:
    - componentDefRef: redis
      monitor: true
      name: redis
      replicas: {{ .Values.redis.replicas }}
      resources: {{ toYaml .Values.redis.resources | nindent 8 }}
      serviceAccountName: {{.Values.redis.name}}
      switchPolicy:
        type: Noop
      volumeClaimTemplates:
        - name: data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: {{ .Values.redis.storage }}
    {{- if gt (int .Values.redis.sentinelReplicas) 0 }}
    - componentDefRef: redis-sentinel
      monitor: true
      name: redis-sentinel
      replicas: {{ .Values.redis.sentinelReplicas }}
      resources: {{ toYaml .Values.redis.sentinelResources | nindent 8 }}
      serviceAccountName: {{.Values.redis.name}}
      switchPolicy:
        type: Noop
      volumeClaimTemplates:
        - name: data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: {{ .Values.redis.storage }}
    {{- end }}
  terminationPolicy: Delete
